swagger: "2.0"
info:
  description: Metamodel Specification
  title: Metamodel Specification
  version: 1.6.0
basePath: /api
paths:
  /metamodel:
    get:
      responses:
        "200":
          description: model model response
          schema:
            type: array
            items:
              - $ref: "#/definitions/MetaData"
              - $ref: "#/definitions/include"
definitions:
# MetaData Starts
  MetaData:
    required:
      - title
      - name
      - formid
      - resourcelist
      - sections
    properties:
      title:
        type: string
      name:
        type: string
      formid:
        type: string
      resourcelist:
        type: string
      groupid:
        type: string
      category:
        type: string
        enum:
          - tabs
      viewAs:
        type: string
        enum:
          - menu
      hidetitle:
        type: boolean
        default: false
      createButton:
        type: boolean
        default: false
      sections:
        type: array
        items:
          $ref: "#/definitions/Section"
      workflowgrps:
        type: array
        items:
          $ref: "#/definitions/WorkFlowGrp"
# MetaData Ends
# Section Starts: Part of MetaData
  Section:
    type: object
    required:
      - name
      - category
    properties:
      title:
        type: string
      name:
        type: string
      category:
        type: string
        enum:
          - nonaccordion
          - accordion
          - table
          - covtable
      columnsize:
        type: integer
        enum:
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
          - 7
          - 8
          - 9
          - 10
          - 11
          - 12
      searching:
        type: boolean
        default: false
      renderAsTab:
        type: boolean
        default: false
      link:
        type: string
      step:
        type: integer
      visible:
        type: boolean
        default: true
      header:
        type: object
        properties:
          elements:
            type: array
            items:
              - $ref: "#/definitions/InputFieldDefinition"
              - $ref: "#/definitions/SelectFieldDefinition"
              - $ref: "#/definitions/ButtonDefinition"
      sections:
        type: array
        items:
          $ref: "#/definitions/Section"
      elements:
        type: array
        items:
          - $ref: "#/definitions/InputFieldDefinition"
          - $ref: "#/definitions/SelectFieldDefinition"
          - $ref: "#/definitions/ButtonDefinition"
# Section Ends
# WorkFlowGrp Starts: Part of MetaData
  WorkFlowGrp:
    type: object
    properties:
      flowgrps:
        type: array
        items:
          $ref: "#/definitions/FlowGrp"
# WorkFlowGrp Ends
# InputFieldDefinition Starts: Part of Section
  InputFieldDefinition:
    type: object
    required:
      - name
      - type
      - label
      - columnsize
    properties:
      name:
        type: string
      type:
        type: string
        enum:
          - text
          - number
          - date
          - textarea
          - email
          - checkbox
          - label
          - money
          - checkboxgroup
          - richtext
          - autocomplete
      label:
        type: string    
      typewait:
        type: integer
      columnsize:
        type: integer
        enum:
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
          - 7
          - 8
          - 9
          - 10
          - 11
          - 12
      maxlength:
        type: integer
      minlength:
        type: integer
      required:
        type: boolean
        default: false
      visible:
        type: boolean
        default: true
      disabled:
        type: boolean
        default: false
      typeahead:
        type: boolean
        default: false
      mask:
        type: string
      patchOnBlur:
        type: boolean
        default: false
      style:
        type: string
      tabNavigation:
        type: string
# InputFieldDefinition Ends
# SelectFieldDefinition Starts: Part of Section
  SelectFieldDefinition:
    type: object
    required:
      - name
      - type
      - label
      - enumdata
      - columnsize
    properties:
      name:
        type: string
      type:
        type: string
        enum:
          - select
          - dropdown
      label:
        type: string 
      enumdata:
        type: array
        items:
          $ref: "#/definitions/OptionDefinition"  
      columnsize:
        type: integer
        enum:
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
          - 7
          - 8
          - 9
          - 10
          - 11
          - 12
      required:
        type: boolean
        default: false
      visible:
        type: boolean
        default: true
      style:
        type: string
# SelectFieldDefinition Ends
# OptionDefinition Starts: Part of SelectFieldDefinition
  OptionDefinition:
    type: object
    required:
      - value
      - description
    properties:
      description:
        type: string
      value:
        type: string
# OptionDefinition Ends
# ButtonDefinition Starts: Part of Section
  ButtonDefinition:
    type: object
    required:
      - name
      - type
      - label
      - columnsize
    properties:
      name:
        type: string
      type:
        type: string
        enum:
          - button
          - link
          - buttonSmall
      label:
        type: string
      columnsize:
        type: integer
        enum:
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
          - 7
          - 8
          - 9
          - 10
          - 11
          - 12
      icon:
        type: string
      action:
        type: string
      onclick:
        type: string
      style:
        type: string
# ButtonDefinition Ends
# FlowGrp Starts: Part of WorkFlowGrp
  FlowGrp:
    type: object
    required:
      - name
      - label
      - completed
      - doneclass
      - columnsize
    properties:
      name:
        type: string
      label:
        type: string
      completed:
        type: string
        enum:
          - complete
          - disabled
      classname:
        type: string
      actionurl:
        type: string
      doneclass:
        type: string
      columnsize:
        type: integer
        enum:
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
          - 7
          - 8
          - 9
          - 10
          - 11
          - 12
# FlowGrp Ends
# Include Starts
  include:
    type: array
    items:
      $ref: "#/definitions/TabNames"
# Include Ends
# TabNames Starts: Part of Include
  TabNames:
    type: string
# TabNames Ends