



INSERT [dbo].[USER_PERSONALIZATION] ([USERNAME], [APPS_ADDED], [USER_HOME_SCREEN], [USER_GREETING], [USER_BANNER], [USER_THEME], [USER_FONT], [USER_OPTIONBAR], [FAVOURITE_EXPRSPROC]) VALUES ('user', '1,2,4,3,6,5,7,8,9', '{"list":[{"icon":"iconPolicyProcessing","title":"Policy Processing","epheader":"Express Processing","appadded":"yes","appname":"PolicyProcess","target":"policyProcessing","tab_list":[{"title":"Creates a new Policy","text":"New Business","class":"active","links":[{"id":"New_Business","isExpressProcsOption":"yes","icon":"App_NewBusiness.png","text":"Creates a new Policy","title":"New Business","url":"/screen/Policy_Processing_NB","linkno":"1"}],"tabid":1},{"title":"Search the existing policy","text":"Policy Search","class":null,"links":[{"id":"Policy_Search","isExpressProcsOption":"no","icon":"App_Inquiry.png","text":"Search the existing policy","title":"Policy Search","url":"/screen/Policy_Search","linkno":"2"},{"id":"Policy_Tracking","isExpressProcsOption":"no","icon":"App_AddItem.png","text":"Tracks the policy","title":"Policy Tracking","url":"#","linkno":"3"}],"tabid":2},{"title":"Tracks the policy","text":"Policy Tracking","class":null,"links":[],"tabid":3}],"expressprocessing":"yes"},{"icon":"iconQuoteProcessing","title":"Quote Processing","epheader":"Express Quote","appadded":"yes","appname":"QuoteProcess","target":"quoteProcessing","tab_list":[{"title":"Creates a new Policy","text":"New Business","class":"active","links":[{"id":"New_Business","isExpressProcsOption":"yes","icon":"App_NewBusiness.png","text":"Creates a new Policy","title":"New Business","url":"/screen/Policy_Processing_NB","linkno":"4"}],"tabid":4},{"title":"Search the existing policy","text":"Policy Search","class":null,"links":[],"tabid":5}],"expressprocessing":"yes"},{"icon":"iconClaim","title":"Claims","epheader":null,"appadded":"no","appname":"ClaimProcess","target":"claimProcessing","tab_list":[],"expressprocessing":"no"},{"icon":"iconBilling","title":"Billing2","epheader":null,"appadded":"no","appname":"Billing","target":"billingProcessing","tab_list":[],"expressprocessing":"no"}]}', 'Welcome', 'Mountain', 'csctheme', 'Verdana', 'top', '4,3,1,2')
INSERT [dbo].[USER_PERSONALIZATION] ([USERNAME], [APPS_ADDED], [USER_HOME_SCREEN], [USER_GREETING], [USER_BANNER], [USER_THEME], [USER_FONT], [USER_OPTIONBAR], [FAVOURITE_EXPRSPROC]) VALUES ('admin', '1,2,', '', 'Welcome', 'Default', 'csctheme', 'Arial', 'top', '2,3,1')



-----------------------------------------------------------------------------------------------------------------------







INSERT [dbo].[APPLICATIONS] ([APP_ID], [APPNAME], [APP_TITLE], [APP_ICON], [APP_TARGET], [EXPRESSPROCESSING], [EPHEADER], [APP_URL]) VALUES (5, 'New Business', 'New Business', 'iconNewBusiness', '', 'no', NULL, '/screen/Policy_Processing_NB_PP01/Add')
INSERT [dbo].[APPLICATIONS] ([APP_ID], [APPNAME], [APP_TITLE], [APP_ICON], [APP_TARGET], [EXPRESSPROCESSING], [EPHEADER], [APP_URL]) VALUES (6, 'Policy Search', 'Policy Search', 'iconInquiry', '', 'no', NULL, '/screen/Policy_Search/Search')
INSERT [dbo].[APPLICATIONS] ([APP_ID], [APPNAME], [APP_TITLE], [APP_ICON], [APP_TARGET], [EXPRESSPROCESSING], [EPHEADER], [APP_URL]) VALUES (1, 'PolicyProcess', 'Policy Processing', 'iconPolicyProcessing', 'policyProcessing', 'yes', 'Express Processing', NULL)
INSERT [dbo].[APPLICATIONS] ([APP_ID], [APPNAME], [APP_TITLE], [APP_ICON], [APP_TARGET], [EXPRESSPROCESSING], [EPHEADER], [APP_URL]) VALUES (2, 'QuoteProcess', 'Quote Processing', 'iconQuoteProcessing', 'quoteProcessing', 'yes', 'Express Quote', NULL)
INSERT [dbo].[APPLICATIONS] ([APP_ID], [APPNAME], [APP_TITLE], [APP_ICON], [APP_TARGET], [EXPRESSPROCESSING], [EPHEADER], [APP_URL]) VALUES (3, 'ClaimProcess', 'Claims', 'iconClaim', 'claimProcessing', 'no', NULL, NULL)
INSERT [dbo].[APPLICATIONS] ([APP_ID], [APPNAME], [APP_TITLE], [APP_ICON], [APP_TARGET], [EXPRESSPROCESSING], [EPHEADER], [APP_URL]) VALUES (4, 'Billing', 'Billing', 'iconBilling', 'billingProcessing', 'no', NULL, NULL)
INSERT [dbo].[APPLICATIONS] ([APP_ID], [APPNAME], [APP_TITLE], [APP_ICON], [APP_TARGET], [EXPRESSPROCESSING], [EPHEADER], [APP_URL]) VALUES  (7, 'System Control', 'System Control', 'iconSystemControl', 'systemControlProcessing', 'no', NULL, NULL)
INSERT [dbo].[APPLICATIONS] ([APP_ID], [APPNAME], [APP_TITLE], [APP_ICON], [APP_TARGET], [EXPRESSPROCESSING], [EPHEADER], [APP_URL]) VALUES  (8, 'Operations Control', 'Operations Control', 'iconOperationsControl', 'operationControlProcessing', 'no', NULL, NULL)
INSERT [dbo].[APPLICATIONS] ([APP_ID], [APPNAME], [APP_TITLE], [APP_ICON], [APP_TARGET], [EXPRESSPROCESSING], [EPHEADER], [APP_URL]) VALUES  (9, 'Reports', 'Reports', 'iconReports', 'reportsProcessing', 'no', NULL, NULL)
INSERT [dbo].[APPLICATIONS] ([APP_ID], [APPNAME], [APP_TITLE], [APP_ICON], [APP_TARGET], [EXPRESSPROCESSING], [EPHEADER], [APP_URL]) VALUES (11, 'Agency File', 'Agency File', 'iconPolicyProcessing', 'agencyFile', 'no', NULL, NULL)
INSERT [dbo].[APPLICATIONS] ([APP_ID], [APPNAME], [APP_TITLE], [APP_ICON], [APP_TARGET], [EXPRESSPROCESSING], [EPHEADER], [APP_URL]) VALUES (12, 'Receivables', 'Receivables', 'iconPolicyProcessing', 'receivables', 'no', NULL, NULL)







--------------------------------------------------------------------------------



INSERT [dbo].[APPLICATION_TABS] ([TAB_ID], [TAB_TEXT], [TAB_TITLE], [TAB_CLASS], [ASSOCIATED_APPLICATION]) VALUES (3, 'Client_Search', 'Client_Search', NULL, '1')
INSERT [dbo].[APPLICATION_TABS] ([TAB_ID], [TAB_TEXT], [TAB_TITLE], [TAB_CLASS], [ASSOCIATED_APPLICATION]) VALUES (1, 'New Business', 'Creates a new Policy', 'active', '1')
INSERT [dbo].[APPLICATION_TABS] ([TAB_ID], [TAB_TEXT], [TAB_TITLE], [TAB_CLASS], [ASSOCIATED_APPLICATION]) VALUES (2, 'Policy Search', 'Search the existing policy', NULL, '1')
INSERT [dbo].[APPLICATION_TABS] ([TAB_ID], [TAB_TEXT], [TAB_TITLE], [TAB_CLASS], [ASSOCIATED_APPLICATION]) VALUES (4, 'New Quote', 'Creates a new Quote', 'active', '2')
INSERT [dbo].[APPLICATION_TABS] ([TAB_ID], [TAB_TEXT], [TAB_TITLE], [TAB_CLASS], [ASSOCIATED_APPLICATION]) VALUES (5, 'Quote Search', 'Search the existing Quote', NULL, '2')
INSERT [dbo].[APPLICATION_TABS] ([TAB_ID], [TAB_TEXT], [TAB_TITLE], [TAB_CLASS], [ASSOCIATED_APPLICATION]) VALUES (6, 'Customer Search', 'Search the Customer', NULL, '1')
INSERT [dbo].[APPLICATION_TABS] ([TAB_ID], [TAB_TEXT], [TAB_TITLE], [TAB_CLASS], [ASSOCIATED_APPLICATION]) VALUES (15, 'Bureau Crit Tracking', 'Bureau Crit Tracking', NULL , '1')
INSERT [dbo].[APPLICATION_TABS] ([TAB_ID], [TAB_TEXT], [TAB_TITLE], [TAB_CLASS], [ASSOCIATED_APPLICATION]) VALUES (18, 'Transfer Utility', 'Transfer Utility', NULL, '1')
INSERT [dbo].[APPLICATION_TABS] ([TAB_ID], [TAB_TEXT], [TAB_TITLE], [TAB_CLASS], [ASSOCIATED_APPLICATION]) VALUES (16, 'State Surcharge Report', 'State Surcharge Report', NULL , '9')
INSERT [dbo].[APPLICATION_TABS] ([TAB_ID], [TAB_TEXT], [TAB_TITLE], [TAB_CLASS], [ASSOCIATED_APPLICATION]) VALUES (17, 'Service Standards Report', 'Service Standards Report', NULL , '9')
INSERT [dbo].[APPLICATION_TABS] ([TAB_ID], [TAB_TEXT], [TAB_TITLE], [TAB_CLASS], [ASSOCIATED_APPLICATION]) VALUES (7,'On Request Operations','Report Output Viewer','active','7')
INSERT [dbo].[APPLICATION_TABS] ([TAB_ID], [TAB_TEXT], [TAB_TITLE], [TAB_CLASS], [ASSOCIATED_APPLICATION]) VALUES (8,'Processing/Reporting Cycles','Processing/Reporting Cycles','active','8') 
INSERT [dbo].[APPLICATION_TABS] ([TAB_ID], [TAB_TEXT], [TAB_TITLE], [TAB_CLASS], [ASSOCIATED_APPLICATION]) VALUES (9, 'PICS', 'Policy Insurance Capturing System', NULL, '8')
INSERT [dbo].[APPLICATION_TABS] ([TAB_ID], [TAB_TEXT], [TAB_TITLE], [TAB_CLASS], [ASSOCIATED_APPLICATION]) VALUES (10, 'Change System Override Date', 'Change System Override Date', NULL, '8')
INSERT [dbo].[APPLICATION_TABS] ([TAB_ID], [TAB_TEXT], [TAB_TITLE], [TAB_CLASS], [ASSOCIATED_APPLICATION]) VALUES (11, 'Unit Statistical', 'Unit Statistical', NULL, '8')
INSERT [dbo].[APPLICATION_TABS] ([TAB_ID], [TAB_TEXT], [TAB_TITLE], [TAB_CLASS], [ASSOCIATED_APPLICATION]) VALUES (12, 'Reports', 'Reports', 'active', '9')
INSERT [dbo].[APPLICATION_TABS] ([TAB_ID], [TAB_TEXT], [TAB_TITLE], [TAB_CLASS], [ASSOCIATED_APPLICATION]) VALUES (13, 'Retrospective Rating Details', 'Retrospective Rating Details', NULL, '1')
INSERT [dbo].[APPLICATION_TABS] ([TAB_ID], [TAB_TEXT], [TAB_TITLE], [TAB_CLASS], [ASSOCIATED_APPLICATION]) VALUES (14, 'Underwriting Activity', 'Search Underwriting Activity', NULL, '1')
INSERT [dbo].[APPLICATION_TABS] ([TAB_ID], [TAB_TEXT], [TAB_TITLE], [TAB_CLASS], [ASSOCIATED_APPLICATION]) VALUES (19, 'Agency File Maintenance', 'Maintain Agency File Info', 'active', '11')
INSERT [dbo].[APPLICATION_TABS] ([TAB_ID], [TAB_TEXT], [TAB_TITLE], [TAB_CLASS], [ASSOCIATED_APPLICATION]) VALUES (20, 'Agency Transfer', 'Agency Transfer', NULL, '11')
INSERT [dbo].[APPLICATION_TABS] ([TAB_ID], [TAB_TEXT], [TAB_TITLE], [TAB_CLASS], [ASSOCIATED_APPLICATION]) VALUES (21, 'Sub Producer Maintenance', 'Sub Producer Maintenance', NULL, '11')
INSERT [dbo].[APPLICATION_TABS] ([TAB_ID], [TAB_TEXT], [TAB_TITLE], [TAB_CLASS], [ASSOCIATED_APPLICATION]) VALUES (22, 'Policy Search', 'Receivables Policy Search', 'active', '12')
INSERT [dbo].[APPLICATION_TABS] ([TAB_ID], [TAB_TEXT], [TAB_TITLE], [TAB_CLASS], [ASSOCIATED_APPLICATION]) VALUES (23, 'Customer Search', 'Customer Search', 'active', '12')
INSERT [dbo].[APPLICATION_TABS] ([TAB_ID], [TAB_TEXT], [TAB_TITLE], [TAB_CLASS], [ASSOCIATED_APPLICATION]) VALUES (24, 'Direct Bill Customer Bill', 'Direct Bill Customer Bill', null, '12')
INSERT [dbo].[APPLICATION_TABS] ([TAB_ID], [TAB_TEXT], [TAB_TITLE], [TAB_CLASS], [ASSOCIATED_APPLICATION]) VALUES (25, 'Payment Search DB/CB', 'Payment Search DB/CB', null, '12')
INSERT [dbo].[APPLICATION_TABS] ([TAB_ID], [TAB_TEXT], [TAB_TITLE], [TAB_CLASS], [ASSOCIATED_APPLICATION]) VALUES (26, 'Agency Bill', 'Agency Bill', null, '12')
INSERT [dbo].[APPLICATION_TABS] ([TAB_ID], [TAB_TEXT], [TAB_TITLE], [TAB_CLASS], [ASSOCIATED_APPLICATION]) VALUES (27, 'Broker Bill', 'Broker Bill', null, '12')
INSERT [dbo].[APPLICATION_TABS] ([TAB_ID], [TAB_TEXT], [TAB_TITLE], [TAB_CLASS], [ASSOCIATED_APPLICATION]) VALUES (28, 'ACH Transmittal Process', 'ACH Transmittal Process', null, '12')
INSERT [dbo].[APPLICATION_TABS] ([TAB_ID], [TAB_TEXT], [TAB_TITLE], [TAB_CLASS], [ASSOCIATED_APPLICATION]) VALUES (29, 'Remittance Processing', 'Remittance Processing', null, '12')
INSERT [dbo].[APPLICATION_TABS] ([TAB_ID], [TAB_TEXT], [TAB_TITLE], [TAB_CLASS], [ASSOCIATED_APPLICATION]) VALUES (30, 'Cash Accounting Period', 'Cash Accounting Period', null, '12')
INSERT [dbo].[APPLICATION_TABS] ([TAB_ID], [TAB_TEXT], [TAB_TITLE], [TAB_CLASS], [ASSOCIATED_APPLICATION]) VALUES (31, 'Dunning', 'Dunning', null, '12')


-----------------------------------------------------------------



INSERT [dbo].[APPLICATION_TAB_LINKS] ([LINK_NO], [LINK_ID], [LINK_TITLE], [LINK_ICON], [LINK_URL], [LINK_TEXT], [EXPRESS_PROCS], [ASSOCIATED_TABID], [LINK_ACTION]) VALUES (1, 'New_Business', 'New Business', 'App_NewBusiness.png', '/screen/Policy_Processing_NB_PP01', 'Creates a new Policy', 'yes', '1', 'Add')
INSERT [dbo].[APPLICATION_TAB_LINKS] ([LINK_NO], [LINK_ID], [LINK_TITLE], [LINK_ICON], [LINK_URL], [LINK_TEXT], [EXPRESS_PROCS], [ASSOCIATED_TABID], [LINK_ACTION]) VALUES (2, 'Policy_Search', 'Policy Search', 'App_Inquiry.png', '/screen/Policy_Search', 'Search the existing policy', 'yes', '2', 'Search')
INSERT [dbo].[APPLICATION_TAB_LINKS] ([LINK_NO], [LINK_ID], [LINK_TITLE], [LINK_ICON], [LINK_URL], [LINK_TEXT], [EXPRESS_PROCS], [ASSOCIATED_TABID], [LINK_ACTION]) VALUES (4, 'New_Quote', 'New Quote', 'App_NewBusiness.png', '/screen/POINT_APPLICATION_INFORMATION_QUOTES_PROC', 'Creates a new Quote', 'yes', '4', 'Add')
INSERT [dbo].[APPLICATION_TAB_LINKS] ([LINK_NO], [LINK_ID], [LINK_TITLE], [LINK_ICON], [LINK_URL], [LINK_TEXT], [EXPRESS_PROCS], [ASSOCIATED_TABID], [LINK_ACTION]) VALUES (5, 'Quote_Search', 'Quote Search', 'App_Inquiry.png', '/screen/Quote_Search', 'Search the existing policy', 'yes', '5', 'Search')
INSERT [dbo].[APPLICATION_TAB_LINKS] ([LINK_NO], [LINK_ID], [LINK_TITLE], [LINK_ICON], [LINK_URL], [LINK_TEXT], [EXPRESS_PROCS], [ASSOCIATED_TABID], [LINK_ACTION]) VALUES (3, 'Client_Search', 'Client_Search', 'App_Client.png', '/screen/Client_Search', 'Search the client', NULL, '3', 'Add')
INSERT [dbo].[APPLICATION_TAB_LINKS] ([LINK_NO], [LINK_ID], [LINK_TITLE], [LINK_ICON], [LINK_URL], [LINK_TEXT], [EXPRESS_PROCS], [ASSOCIATED_TABID], [LINK_ACTION]) VALUES (6, 'Customer_Search', 'Customer Search', 'App_Client.png', '/screen/PolCustomerSearchHeader', 'Search the customer', NULL, '6', 'Add')
INSERT [dbo].[APPLICATION_TAB_LINKS] ([LINK_NO], [LINK_ID], [LINK_TITLE], [LINK_ICON], [LINK_URL], [LINK_TEXT], [EXPRESS_PROCS], [ASSOCIATED_TABID], [LINK_ACTION]) VALUES (28, 'Bureau Crit Tracking', 'Bureau Crit Tracking', 'App_NewBusiness.png', '/screen/PolBureauCritTrackingListHeader', 'Bureau Crit Tracking', NULL, '15', 'Add')
INSERT [dbo].[APPLICATION_TAB_LINKS] ([LINK_NO], [LINK_ID], [LINK_TITLE], [LINK_ICON], [LINK_URL], [LINK_TEXT], [EXPRESS_PROCS], [ASSOCIATED_TABID], [LINK_ACTION]) VALUES (33, 'Field Underwriter', 'Field Underwriter', 'App_NewBusiness.png', '/screen/WcpUnderWriter', 'Underwriter Transfer', NULL, '18', 'Add')
INSERT [dbo].[APPLICATION_TAB_LINKS] ([LINK_NO], [LINK_ID], [LINK_TITLE], [LINK_ICON], [LINK_URL], [LINK_TEXT], [EXPRESS_PROCS], [ASSOCIATED_TABID], [LINK_ACTION]) VALUES (32, 'Loss Prevention Rep', 'Loss Prevention Rep', 'App_NewBusiness.png', '/screen/WcpTransferUtility', 'Loss Prevention Transfer Utility', NULL, '18', 'Add')
INSERT [dbo].[APPLICATION_TAB_LINKS] ([LINK_NO], [LINK_ID], [LINK_TITLE], [LINK_ICON], [LINK_URL], [LINK_TEXT], [EXPRESS_PROCS], [ASSOCIATED_TABID], [LINK_ACTION]) VALUES (30, 'State Surcharge Report', 'State Surcharge Report', 'App_NewBusiness.png', '/screen/RptStateSurcharge', 'Submit State Surcharge Report', NULL, '16', 'Add')
INSERT [dbo].[APPLICATION_TAB_LINKS] ([LINK_NO], [LINK_ID], [LINK_TITLE], [LINK_ICON], [LINK_URL], [LINK_TEXT], [EXPRESS_PROCS], [ASSOCIATED_TABID], [LINK_ACTION]) VALUES (31, 'Service Standards Report', 'Service Standards Report', 'App_NewBusiness.png', '/screen/RptServiceStandardReportSubmission', 'Submit Service Standards Report', NULL, '17', 'Add')
INSERT [dbo].[APPLICATION_TAB_LINKS] ([LINK_NO], [LINK_ID], [LINK_TITLE], [LINK_ICON], [LINK_URL], [LINK_TEXT], [EXPRESS_PROCS], [ASSOCIATED_TABID], [LINK_ACTION]) VALUES (7, 'Report_Output_Viewer', 'Report Output Viewer', 'App_NewBusiness.png', '/screen/PrintFileList', 'View the reports', 'NULL', '7', 'Add')
INSERT [dbo].[APPLICATION_TAB_LINKS] ([LINK_NO], [LINK_ID], [LINK_TITLE], [LINK_ICON], [LINK_URL], [LINK_TEXT], [EXPRESS_PROCS], [ASSOCIATED_TABID], [LINK_ACTION]) VALUES (8, 'List_Active_Tasks', 'List Active Tasks', 'App_NewBusiness.png', '/screen/ScheduledJobsListFrame', 'View active list tasks', 'NULL', '7', 'Add')
INSERT [dbo].[APPLICATION_TAB_LINKS] ([LINK_NO], [LINK_ID], [LINK_TITLE], [LINK_ICON], [LINK_URL], [LINK_TEXT], [EXPRESS_PROCS], [ASSOCIATED_TABID], [LINK_ACTION]) VALUES (9, 'Policy_Pull_Utility', 'Policy Pull Utility', 'App_NewBusiness.png', '/screen/EnterPolicyKeyToPull', 'Utility for pulling the policy', 'NULL', '7', 'Add')
INSERT [dbo].[APPLICATION_TAB_LINKS] ([LINK_NO], [LINK_ID], [LINK_TITLE], [LINK_ICON], [LINK_URL], [LINK_TEXT], [EXPRESS_PROCS], [ASSOCIATED_TABID], [LINK_ACTION]) VALUES (10, 'Daily Cycle', 'Daily Cycle', 'App_NewBusiness.png', '/screen/BasReports', 'Daily cycle processing', 'NULL', '8', 'Add')
INSERT [dbo].[APPLICATION_TAB_LINKS] ([LINK_NO], [LINK_ID], [LINK_TITLE], [LINK_ICON], [LINK_URL], [LINK_TEXT], [EXPRESS_PROCS], [ASSOCIATED_TABID], [LINK_ACTION]) VALUES (11, 'Month End Processing', 'Month End Processing', 'App_NewBusiness.png', '/screen/BasReports', 'Month End Processing', 'NULL', '8', 'Add')
INSERT [dbo].[APPLICATION_TAB_LINKS] ([LINK_NO], [LINK_ID], [LINK_TITLE], [LINK_ICON], [LINK_URL], [LINK_TEXT], [EXPRESS_PROCS], [ASSOCIATED_TABID], [LINK_ACTION]) VALUES (12, 'Earned Reinsurance Generation', 'Earned Reinsurance Generation', 'App_NewBusiness.png', '/screen/BasReports', 'Earned Reinsurance Generation', 'NULL', '8', 'Add')
INSERT [dbo].[APPLICATION_TAB_LINKS] ([LINK_NO], [LINK_ID], [LINK_TITLE], [LINK_ICON], [LINK_URL], [LINK_TEXT], [EXPRESS_PROCS], [ASSOCIATED_TABID], [LINK_ACTION]) VALUES (13, 'General Ledger Interface', 'General Ledger Interface', 'App_NewBusiness.png', '/screen/GeneralLedgerInterface', 'General Ledger Interface', 'NULL', '8', 'Add')
INSERT [dbo].[APPLICATION_TAB_LINKS] ([LINK_NO], [LINK_ID], [LINK_TITLE], [LINK_ICON], [LINK_URL], [LINK_TEXT], [EXPRESS_PROCS], [ASSOCIATED_TABID], [LINK_ACTION]) VALUES (14, 'Bulk Monthly File Build', 'Bulk Monthly File Build', 'App_NewBusiness.png', '/screen/BasReports', 'Bulk Monthly File Build', 'NULL', '8', 'Add')
INSERT [dbo].[APPLICATION_TAB_LINKS] ([LINK_NO], [LINK_ID], [LINK_TITLE], [LINK_ICON], [LINK_URL], [LINK_TEXT], [EXPRESS_PROCS], [ASSOCIATED_TABID], [LINK_ACTION]) VALUES (15, 'Policy Issuance Capturing System', 'Policy Insurance Capturing System', 'App_NewBusiness.png', '/screen/PolicyIssuanceCapturingReport', 'Policy Insurance Capturing System', 'NULL', '9', 'Add')
INSERT [dbo].[APPLICATION_TAB_LINKS] ([LINK_NO], [LINK_ID], [LINK_TITLE], [LINK_ICON], [LINK_URL], [LINK_TEXT], [EXPRESS_PROCS], [ASSOCIATED_TABID], [LINK_ACTION]) VALUES (16, 'Selective PICS Processing', 'Selective PICS Processing', 'App_NewBusiness.png', '/screen/SelectivePICSProcessing', 'Selective PICS Processing', 'NULL', '9', 'Add')
INSERT [dbo].[APPLICATION_TAB_LINKS] ([LINK_NO], [LINK_ID], [LINK_TITLE], [LINK_ICON], [LINK_URL], [LINK_TEXT], [EXPRESS_PROCS], [ASSOCIATED_TABID], [LINK_ACTION]) VALUES (17, 'Unit Statistical Report', 'Unit Statistical Report', 'App_NewBusiness.png', '/screen/UnitStatisticalReport', 'Unit Statistical Report', 'NULL', '11', 'Add')
INSERT [dbo].[APPLICATION_TAB_LINKS] ([LINK_NO], [LINK_ID], [LINK_TITLE], [LINK_ICON], [LINK_URL], [LINK_TEXT], [EXPRESS_PROCS], [ASSOCIATED_TABID], [LINK_ACTION]) VALUES (18, 'Unit Statistical Report', 'Unit Statistical Report', 'App_NewBusiness.png', '/screen/UnitStatisticalReport', 'Unit Statistical Report', 'NULL', '11', 'Add')
INSERT [dbo].[APPLICATION_TAB_LINKS] ([LINK_NO], [LINK_ID], [LINK_TITLE], [LINK_ICON], [LINK_URL], [LINK_TEXT], [EXPRESS_PROCS], [ASSOCIATED_TABID], [LINK_ACTION]) VALUES (19, 'Unit Statistical Inquiry', 'Unit Statistical Inquiry', 'App_NewBusiness.png', '/screen/SelUnitRptErrCorrection', 'Unit Statistical Inquiry', 'NULL', '11', 'Add')
INSERT [dbo].[APPLICATION_TAB_LINKS] ([LINK_NO], [LINK_ID], [LINK_TITLE], [LINK_ICON], [LINK_URL], [LINK_TEXT], [EXPRESS_PROCS], [ASSOCIATED_TABID], [LINK_ACTION]) VALUES (20, 'Unit Statistical Delete', 'Unit Statistical Delete', 'App_NewBusiness.png', '/screen/UnitStatisticalDelete', 'Unit Statistical Delete', 'NULL', '11', 'Add')
INSERT [dbo].[APPLICATION_TAB_LINKS] ([LINK_NO], [LINK_ID], [LINK_TITLE], [LINK_ICON], [LINK_URL], [LINK_TEXT], [EXPRESS_PROCS], [ASSOCIATED_TABID], [LINK_ACTION]) VALUES (21, 'Unit Statistical Re-Archive', 'Unit Statistical Re-Archive', 'App_NewBusiness.png', '/screen/UnitStatisticalReArchive', 'Unit Statistical Re-Archive', 'NULL', '11', 'Add')
INSERT [dbo].[APPLICATION_TAB_LINKS] ([LINK_NO], [LINK_ID], [LINK_TITLE], [LINK_ICON], [LINK_URL], [LINK_TEXT], [EXPRESS_PROCS], [ASSOCIATED_TABID], [LINK_ACTION]) VALUES (22, 'Unit Stat Reporting - Select and Correct', 'Unit Stat Reporting - Select and Correct', 'App_NewBusiness.png', '/screen/UnitStatProceesRequest', 'Unit Stat Reporting - Select and Correct', 'NULL', '11', 'Add')
INSERT [dbo].[APPLICATION_TAB_LINKS] ([LINK_NO], [LINK_ID], [LINK_TITLE], [LINK_ICON], [LINK_URL], [LINK_TEXT], [EXPRESS_PROCS], [ASSOCIATED_TABID], [LINK_ACTION]) VALUES (23, 'Transfer Unit Stat Archives for CRW', 'Transfer Unit Stat Archives for CRW', 'App_NewBusiness.png', '/screen/UnitStatArchivesForCRW', 'Transfer Unit Stat Archives for CRW', 'NULL', '11', 'Add')
INSERT [dbo].[APPLICATION_TAB_LINKS] ([LINK_NO], [LINK_ID], [LINK_TITLE], [LINK_ICON], [LINK_URL], [LINK_TEXT], [EXPRESS_PROCS], [ASSOCIATED_TABID], [LINK_ACTION]) VALUES (24, 'Reports', 'Reports', 'App_NewBusiness.png', '/reports/BasReports', 'All Reports', 'NULL', '12', 'Add')
INSERT [dbo].[APPLICATION_TAB_LINKS] ([LINK_NO], [LINK_ID], [LINK_TITLE], [LINK_ICON], [LINK_URL], [LINK_TEXT], [EXPRESS_PROCS], [ASSOCIATED_TABID], [LINK_ACTION]) VALUES (25, 'Loss History Report for Retro Policies', 'Loss History Report for Retro Policies', 'App_NewBusiness.png', '/screen/PolRetroLossHistoryReport', 'PolRetroLossHistoryReport', 'NULL', '13', 'Add')
INSERT [dbo].[APPLICATION_TAB_LINKS] ([LINK_NO], [LINK_ID], [LINK_TITLE], [LINK_ICON], [LINK_URL], [LINK_TEXT], [EXPRESS_PROCS], [ASSOCIATED_TABID], [LINK_ACTION]) VALUES (26, 'Underwriting_Activity_Search', 'Underwriting Activity Search', 'App_UnderwritingActivity.png', '/screen/UndActivitySearchHeader', 'Search the UW Activity', 'NULL', '14', 'Search')
INSERT [dbo].[APPLICATION_TAB_LINKS] ([LINK_NO], [LINK_ID], [LINK_TITLE], [LINK_ICON], [LINK_URL], [LINK_TEXT], [EXPRESS_PROCS], [ASSOCIATED_TABID], [LINK_ACTION]) VALUES (34, 'Agency_File', 'Agency File', 'App_NewBusiness.png', '/screen/AgnSearchHeader', 'Search the Agency', NULL, '19', 'Search')
INSERT [dbo].[APPLICATION_TAB_LINKS] ([LINK_NO], [LINK_ID], [LINK_TITLE], [LINK_ICON], [LINK_URL], [LINK_TEXT], [EXPRESS_PROCS], [ASSOCIATED_TABID], [LINK_ACTION]) VALUES (35, 'Receivables', 'Receivables Policy Search', 'App_NewBusiness.png', '/screen/RcvPolicySearch', 'Search the Policy in Receivables', NULL, '22', 'Search')
INSERT [dbo].[APPLICATION_TAB_LINKS] ([LINK_NO], [LINK_ID], [LINK_TITLE], [LINK_ICON], [LINK_URL], [LINK_TEXT], [EXPRESS_PROCS], [ASSOCIATED_TABID], [LINK_ACTION]) VALUES (36, 'Receivables_Customer_Search', 'Receivables Customer Search', 'App_NewBusiness.png', '/screen/RcvCBCustomerSearch', 'Search the Customer in Receivables', NULL, '23', 'Search')
INSERT [dbo].[APPLICATION_TAB_LINKS] ([LINK_NO], [LINK_ID], [LINK_TITLE], [LINK_ICON], [LINK_URL], [LINK_TEXT], [EXPRESS_PROCS], [ASSOCIATED_TABID], [LINK_ACTION]) VALUES (37, 'Payment Search DB/CB', 'Payment Search DB/CB', 'App_NewBusiness.png', '/screen/RcvDBPmtAdjustmentSearchFrame', 'Payment Search in Receivables', NULL, '25', 'Search')
INSERT [dbo].[APPLICATION_TAB_LINKS] ([LINK_NO], [LINK_ID], [LINK_TITLE], [LINK_ICON], [LINK_URL], [LINK_TEXT], [EXPRESS_PROCS], [ASSOCIATED_TABID], [LINK_ACTION]) VALUES (38, 'Agency Search', 'Agency Search', 'App_NewBusiness.png', '/screen/RcvABAgencySearchFrame', 'Agency Search in Receivables', NULL, '26', 'Search')
INSERT [dbo].[APPLICATION_TAB_LINKS] ([LINK_NO], [LINK_ID], [LINK_TITLE], [LINK_ICON], [LINK_URL], [LINK_TEXT], [EXPRESS_PROCS], [ASSOCIATED_TABID], [LINK_ACTION]) VALUES (39, 'Payment Entry / Batch List', 'Payment Entry / Batch List', 'App_NewBusiness.png', '/screen/RcvABCashBatchListFrame', 'Payment Entry in Receivables', NULL, '26', 'Add')
INSERT [dbo].[APPLICATION_TAB_LINKS] ([LINK_NO], [LINK_ID], [LINK_TITLE], [LINK_ICON], [LINK_URL], [LINK_TEXT], [EXPRESS_PROCS], [ASSOCIATED_TABID], [LINK_ACTION]) VALUES (40, 'Policies with a Credit Balance', 'Policies with a Credit Balance', 'App_NewBusiness.png', '/screen/RcvABPolCreditBalanceFrame', 'Policies with credit balance in Receivables', NULL, '26', 'Search')
INSERT [dbo].[APPLICATION_TAB_LINKS] ([LINK_NO], [LINK_ID], [LINK_TITLE], [LINK_ICON], [LINK_URL], [LINK_TEXT], [EXPRESS_PROCS], [ASSOCIATED_TABID], [LINK_ACTION]) VALUES (41, 'Suspended Agency Payments', 'Suspended Agency Payments', 'App_NewBusiness.png', '/screen/RcvABSuspAgnPaymentsFrame', 'Suspended Agency Payments in Receivables', NULL, '26', 'Search')
INSERT [dbo].[APPLICATION_TAB_LINKS] ([LINK_NO], [LINK_ID], [LINK_TITLE], [LINK_ICON], [LINK_URL], [LINK_TEXT], [EXPRESS_PROCS], [ASSOCIATED_TABID], [LINK_ACTION]) VALUES (42, 'Agency Posting Upload', 'Agency Posting Upload', 'App_NewBusiness.png', '/screen/RcvABPostingUploadFrame', 'Agency Posting Upload in Receivables', NULL, '26', 'Search')
INSERT [dbo].[APPLICATION_TAB_LINKS] ([LINK_NO], [LINK_ID], [LINK_TITLE], [LINK_ICON], [LINK_URL], [LINK_TEXT], [EXPRESS_PROCS], [ASSOCIATED_TABID], [LINK_ACTION]) VALUES (43, 'Suspended Policy Payments', 'Suspended Policy Payments', 'App_NewBusiness.png', '/screen/RcvABSuspPolPaymentsFrame', 'Suspended Policy Payments in Receivables', NULL, '26', 'Search')
INSERT [dbo].[APPLICATION_TAB_LINKS] ([LINK_NO], [LINK_ID], [LINK_TITLE], [LINK_ICON], [LINK_URL], [LINK_TEXT], [EXPRESS_PROCS], [ASSOCIATED_TABID], [LINK_ACTION]) VALUES (44, 'Broker Search', 'Broker Search', 'App_NewBusiness.png', '/screen/RcvBBBrokerSearchFrame', 'Broker Search in Receivables', NULL, '27', 'Search')
INSERT [dbo].[APPLICATION_TAB_LINKS] ([LINK_NO], [LINK_ID], [LINK_TITLE], [LINK_ICON], [LINK_URL], [LINK_TEXT], [EXPRESS_PROCS], [ASSOCIATED_TABID], [LINK_ACTION]) VALUES (45, 'Payment Entry / Batch List', 'Payment Entry / Batch List', 'App_NewBusiness.png', '/screen/RcvBBCashBatchListFrame', 'Payment Entry in Broker Bill', NULL, '27', 'Add')
INSERT [dbo].[APPLICATION_TAB_LINKS] ([LINK_NO], [LINK_ID], [LINK_TITLE], [LINK_ICON], [LINK_URL], [LINK_TEXT], [EXPRESS_PROCS], [ASSOCIATED_TABID], [LINK_ACTION]) VALUES (46, 'Policies with a Credit Balance', 'Policies with a Credit Balance', 'App_NewBusiness.png', '/screen/RcvBBPolCreditBalanceFrame', 'Policies with credit balance in Broker Bill', NULL, '27', 'Search')
INSERT [dbo].[APPLICATION_TAB_LINKS] ([LINK_NO], [LINK_ID], [LINK_TITLE], [LINK_ICON], [LINK_URL], [LINK_TEXT], [EXPRESS_PROCS], [ASSOCIATED_TABID], [LINK_ACTION]) VALUES (47, 'Suspended Broker Payments', 'Suspended Broker Payments', 'App_NewBusiness.png', '/screen/RcvBBSuspBrPaymentsFrame', 'Suspended Broker Payments in Receivables', NULL, '27', 'Search')
INSERT [dbo].[APPLICATION_TAB_LINKS] ([LINK_NO], [LINK_ID], [LINK_TITLE], [LINK_ICON], [LINK_URL], [LINK_TEXT], [EXPRESS_PROCS], [ASSOCIATED_TABID], [LINK_ACTION]) VALUES (48, 'Distribute Invoices', 'Distribute Invoices', 'App_NewBusiness.png', '/screen/RcvBBSendEmailInvToBrokerFrame', 'Distribute Invoices in Receivables', NULL, '27', 'Search')
INSERT [dbo].[APPLICATION_TAB_LINKS] ([LINK_NO], [LINK_ID], [LINK_TITLE], [LINK_ICON], [LINK_URL], [LINK_TEXT], [EXPRESS_PROCS], [ASSOCIATED_TABID], [LINK_ACTION]) VALUES (49, 'Suspended Policy Payments', 'Suspended Policy Payments', 'App_NewBusiness.png', '/screen/RcvBBSuspPolPaymentsFrame', 'Suspended Policy Payments in Broker Bill', NULL, '27', 'Search')
INSERT [dbo].[APPLICATION_TAB_LINKS] ([LINK_NO], [LINK_ID], [LINK_TITLE], [LINK_ICON], [LINK_URL], [LINK_TEXT], [EXPRESS_PROCS], [ASSOCIATED_TABID], [LINK_ACTION]) VALUES (50, 'ACH Transmittal List', 'ACH Transmittal List', 'App_NewBusiness.png', '/screen/AchTranControlFrame', 'ACH Transmittal List in Receivables', NULL, '28', 'Search')
INSERT [dbo].[APPLICATION_TAB_LINKS] ([LINK_NO], [LINK_ID], [LINK_TITLE], [LINK_ICON], [LINK_URL], [LINK_TEXT], [EXPRESS_PROCS], [ASSOCIATED_TABID], [LINK_ACTION]) VALUES (51, 'ACH Control', 'ACH Control', 'App_NewBusiness.png', '/screen/AchControlTableFrame', 'ACH Control in Receivables', NULL, '28', 'Add')
INSERT [dbo].[APPLICATION_TAB_LINKS] ([LINK_NO], [LINK_ID], [LINK_TITLE], [LINK_ICON], [LINK_URL], [LINK_TEXT], [EXPRESS_PROCS], [ASSOCIATED_TABID], [LINK_ACTION]) VALUES (52, 'ACH Bank Holidays', 'ACH Bank Holidays', 'App_NewBusiness.png', '/screen/AchBankHolidayFrame', 'ACH Bank Holidays in Receivables', NULL, '28', 'Add')
INSERT [dbo].[APPLICATION_TAB_LINKS] ([LINK_NO], [LINK_ID], [LINK_TITLE], [LINK_ICON], [LINK_URL], [LINK_TEXT], [EXPRESS_PROCS], [ASSOCIATED_TABID], [LINK_ACTION]) VALUES (53, 'ACH Exception Report', 'ACH Exception Report', 'App_NewBusiness.png', '/screen/AchEFTExcpReportFrame', 'ACH Exception Report in Receivables', NULL, '28', 'Add')
INSERT [dbo].[APPLICATION_TAB_LINKS] ([LINK_NO], [LINK_ID], [LINK_TITLE], [LINK_ICON], [LINK_URL], [LINK_TEXT], [EXPRESS_PROCS], [ASSOCIATED_TABID], [LINK_ACTION]) VALUES (54, 'Remittance Processing', 'Remittance Processing', 'App_NewBusiness.png', '/screen/RcvRemitProcessorUploadFrame', 'Remittance Processing in Receivables', NULL, '29', 'Add')
INSERT [dbo].[APPLICATION_TAB_LINKS] ([LINK_NO], [LINK_ID], [LINK_TITLE], [LINK_ICON], [LINK_URL], [LINK_TEXT], [EXPRESS_PROCS], [ASSOCIATED_TABID], [LINK_ACTION]) VALUES (55, 'Cash Accounting Period', 'Cash Accounting Period', 'App_NewBusiness.png', '/screen/CashAccountingPeriod', 'Cash Accounting Period in Receivables', NULL, '30', 'Add')
INSERT [dbo].[APPLICATION_TAB_LINKS] ([LINK_NO], [LINK_ID], [LINK_TITLE], [LINK_ICON], [LINK_URL], [LINK_TEXT], [EXPRESS_PROCS], [ASSOCIATED_TABID], [LINK_ACTION]) VALUES (56, 'Policies in Collection', 'Policies in Collection', 'App_NewBusiness.png', '/screen/RcvStopCollectionSearchFrame', 'Policies in Collection for Receivables', NULL, '31', 'Search')
INSERT [dbo].[APPLICATION_TAB_LINKS] ([LINK_NO], [LINK_ID], [LINK_TITLE], [LINK_ICON], [LINK_URL], [LINK_TEXT], [EXPRESS_PROCS], [ASSOCIATED_TABID], [LINK_ACTION]) VALUES (57, 'Payment Entry / Batch List', 'Payment Entry / Batch List', 'App_NewBusiness.png', '/screen/RcvDBCashBatchListFrame', 'Entry of Payments in Receivables', NULL, '24', 'Add')
INSERT [dbo].[APPLICATION_TAB_LINKS] ([LINK_NO], [LINK_ID], [LINK_TITLE], [LINK_ICON], [LINK_URL], [LINK_TEXT], [EXPRESS_PROCS], [ASSOCIATED_TABID], [LINK_ACTION]) VALUES (58, 'Policy Suspense', 'Policy Suspense', 'App_NewBusiness.png', '/screen/RcvDBSuspPayListFrame', 'Suspense Policy in Receivables', NULL, '24', 'Search')
INSERT [dbo].[APPLICATION_TAB_LINKS] ([LINK_NO], [LINK_ID], [LINK_TITLE], [LINK_ICON], [LINK_URL], [LINK_TEXT], [EXPRESS_PROCS], [ASSOCIATED_TABID], [LINK_ACTION]) VALUES (59, 'Customer Suspense', 'Customer Suspense', 'App_NewBusiness.png', '/screen/RcvCBSuspCusPaymentsFrame', 'Suspense Customer in Receivables', NULL, '24', 'Search')
INSERT [dbo].[APPLICATION_TAB_LINKS] ([LINK_NO], [LINK_ID], [LINK_TITLE], [LINK_ICON], [LINK_URL], [LINK_TEXT], [EXPRESS_PROCS], [ASSOCIATED_TABID], [LINK_ACTION]) VALUES (60, 'Overpaid Policies List', 'Overpaid Policies List', 'App_NewBusiness.png', '/screen/RcvDBOverpaidListFrame', 'List of Overpaid policies in Receivables', NULL, '24', 'Search')
INSERT [dbo].[APPLICATION_TAB_LINKS] ([LINK_NO], [LINK_ID], [LINK_TITLE], [LINK_ICON], [LINK_URL], [LINK_TEXT], [EXPRESS_PROCS], [ASSOCIATED_TABID], [LINK_ACTION]) VALUES (61, 'Agency Search', 'Agency Search', 'App_NewBusiness.png', '/screen/RcvDBAgencySearchFrame', 'Search of Agency in Receivables', NULL, '24', 'Search')



