<?xml version="1.0" encoding="ISO-8859-1"?>

<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                              xmlns:fo="http://www.w3.org/1999/XSL/Format"
                              xmlns:fn="http://www.w3.org/2005/02/xpath-functions">
	<xsl:include href="ConvertDateCYYMMDDtoMMDDYYYY.xsl"/>
	<xsl:include href="ConvertDateCYYMMDDtoMMDDYY.xsl"/>
	<xsl:include href="ConvertTimeHHMMSS.xsl"/>
	<xsl:include href="Prepad.xsl"/>
	<xsl:include href="Postpad.xsl"/>
	<xsl:param name="date"/>
	<xsl:param name="time"/>
	<xsl:output encoding="UTF-8"/>
	<xsl:preserve-space elements="*"/>

    <xsl:template match="/">
        <fo:root>
            <fo:layout-master-set>
                <fo:simple-page-master master-name="LandscapeReport"
                    page-width="11in"
                    page-height="8.5in"
                    margin-top=".17in"
                    margin-bottom=".17in"
                    margin-left=".25in"
                    margin-right=".25in">
                    <fo:region-body margin-top="0in"/>
                    <fo:region-before extent="0in"/>
                    <fo:region-after  extent="0in"/>
                </fo:simple-page-master>
                <fo:simple-page-master master-name="PortraitReport"
                    page-width="8.5in"
                    page-height="11in"
                    margin-top=".25in"
                    margin-bottom=".25in"
                    margin-left=".17in"
                    margin-right=".17in">
                    <fo:region-body margin-top="0in"/>
                    <fo:region-before extent="0in"/>
                    <fo:region-after  extent="0in"/>
                </fo:simple-page-master>
            </fo:layout-master-set>

            <fo:page-sequence master-reference="LandscapeReport">
                <fo:flow flow-name="xsl-region-body">
                <xsl:apply-templates select="/POINTXML/file/record"/>
                </fo:flow>
            </fo:page-sequence>

        </fo:root>
    </xsl:template>

<!-- Auto Generated XSLT for printer file DDS PMSPUST02-->
<xsl:template match="record[@name = 'PAGENO']" xml:space="preserve">
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre" >                                                                                                     PAGE NO. <fo:page-number/> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre"> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre">
</fo:block>
</xsl:template><xsl:template match="record[@name = 'CARRIER']" xml:space="preserve">
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre" >                                                            ***LINK DATA RECORD***                   POLICY: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="symbol"/></xsl:with-param><xsl:with-param name="len">3</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template><xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="policy0num"/></xsl:with-param><xsl:with-param name="len">7</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre"> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre">     LINK CARRIER CODE........: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="carrcd"/></xsl:with-param><xsl:with-param name="len">5</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>   EXPOSURE STATE......:  <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="risk0state"/></xsl:with-param><xsl:with-param name="len">2</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre">                                        LINK POLICY EFF DATE: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="eff0yr"/></xsl:with-param><xsl:with-param name="len">2</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>/<xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="eff0mo"/></xsl:with-param><xsl:with-param name="len">2</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>/<xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="eff0da"/></xsl:with-param><xsl:with-param name="len">2</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>     REPORT NUMBER: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="rptno"/></xsl:with-param><xsl:with-param name="len">1</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>  CORRECTION SEQUENCE NUMBER: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="corrid"/></xsl:with-param><xsl:with-param name="len">1</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre"> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre"> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre">
</fo:block>
</xsl:template><xsl:template match="record[@name = 'NOPOLRPT']" xml:space="preserve">
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre" >                                                            ***NO UNIT REPORT   GENERATED*** </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre"> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre">     POLICY:  <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="location"/></xsl:with-param><xsl:with-param name="len">2</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>  <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="master0co"/></xsl:with-param><xsl:with-param name="len">2</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>  <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="symbol"/></xsl:with-param><xsl:with-param name="len">3</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>  <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="policy0num"/></xsl:with-param><xsl:with-param name="len">7</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>  <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="module"/></xsl:with-param><xsl:with-param name="len">2</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>     REPORT NUMBER:  <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="rptno"/></xsl:with-param><xsl:with-param name="len">1</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>     CORRECTION SEQUENCE NUMBER:  <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="corrid"/></xsl:with-param><xsl:with-param name="len">1</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre"> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre">       NO SIGNIFICANT CHANGES TO PREVIOUSLY REPORTED DATA FOR ERROR CORRECTION REPORT REQUESTED </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre"> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre"> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre">
</fo:block>
</xsl:template><xsl:template match="record[@name = 'HEADERREC']" xml:space="preserve">
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre" >                                                            ***HEADER RECORD***                      POLICY: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="symbol"/></xsl:with-param><xsl:with-param name="len">3</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template><xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="policy0num"/></xsl:with-param><xsl:with-param name="len">7</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre"> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre">     HEADER RECORD TYPE: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="rectype"/></xsl:with-param><xsl:with-param name="len">1</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>         HEADER LINK DATA....: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="linkdata"/></xsl:with-param><xsl:with-param name="len">40</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre">                                   POLICY EXPIRATION DATE.: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="exp0yr"/></xsl:with-param><xsl:with-param name="len">2</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>/<xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="exp0mo"/></xsl:with-param><xsl:with-param name="len">2</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>/<xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="exp0da"/></xsl:with-param><xsl:with-param name="len">2</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>                            RISK ID NUMBER: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="riskexpid"/></xsl:with-param><xsl:with-param name="len">9</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre">                                   UNIT REPORT RESUBM. IND: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="resubmind"/></xsl:with-param><xsl:with-param name="len">1</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>                                   POLICY TYPE ID CODE: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="typecov"/></xsl:with-param><xsl:with-param name="len">2</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template> <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="planind"/></xsl:with-param><xsl:with-param name="len">2</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template> <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="nonstd"/></xsl:with-param><xsl:with-param name="len">2</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre">     POLICY CONDITIONS: </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre">       ESTIMATED EXPOSURE...: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="estaud"/></xsl:with-param><xsl:with-param name="len">1</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre">       RETROSPECTIVE RATED..: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="retrorate"/></xsl:with-param><xsl:with-param name="len">1</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre">       INTERSTATE RATED.....: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="instrate"/></xsl:with-param><xsl:with-param name="len">1</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>    REPLACEMENT REPT IND: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="replaceind"/></xsl:with-param><xsl:with-param name="len">1</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>       ASWG UNIT IND....: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="aswgind"/></xsl:with-param><xsl:with-param name="len">1</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>           PENDING FILE NO..: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="pendfileno"/></xsl:with-param><xsl:with-param name="len">10</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre">       CANCELED MIDTERM POL.: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="cancelpol"/></xsl:with-param><xsl:with-param name="len">1</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>    CORRECTION TYPE..: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="correction"/></xsl:with-param><xsl:with-param name="len">1</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>          STATE EFF DATE...: <xsl:call-template name="cvtdateCYYMMDDtoMMDDYY"><xsl:with-param name="datefld"><xsl:call-template name="Prepad"><xsl:with-param name="padVar"><xsl:value-of select="stateeffdt"/></xsl:with-param><xsl:with-param name="len">6</xsl:with-param><xsl:with-param name="padChar">0</xsl:with-param></xsl:call-template></xsl:with-param></xsl:call-template>    FED EMP ID NO....: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="fein"/></xsl:with-param><xsl:with-param name="len">9</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre">       THREE YR FIX RATE....: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="threeyrate"/></xsl:with-param><xsl:with-param name="len">1</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>    PREV RPT NUMBER..: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="prevrptno"/></xsl:with-param><xsl:with-param name="len">2</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>         DEDUCTIBLE TYPE..: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="dedtype"/></xsl:with-param><xsl:with-param name="len">4</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>        DEDUCTIBLE % ....: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="dedpcnt"/></xsl:with-param><xsl:with-param name="len">2</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre">       MULTISTATE POLICY....: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="multistate"/></xsl:with-param><xsl:with-param name="len">1</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>    PREV CORRECTION..: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="pcorrect"/></xsl:with-param><xsl:with-param name="len">1</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>          PREV CARRIER CODE: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="pcarrier"/></xsl:with-param><xsl:with-param name="len">5</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>       PREV POLICY NO...: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="ppolno"/></xsl:with-param><xsl:with-param name="len">18</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre">       MCO INDICATOR.......:  <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="apprvmco"/></xsl:with-param><xsl:with-param name="len">1</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>    PREV EXPOSURE ST.: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="pexpst"/></xsl:with-param><xsl:with-param name="len">2</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>         CARRIER USE......: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="carrieruse"/></xsl:with-param><xsl:with-param name="len">12</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>BUREAU USE.......: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="bureauuse"/></xsl:with-param><xsl:with-param name="len">7</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre">                                   PREV POL EFF DT..: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="ppoleff"/></xsl:with-param><xsl:with-param name="len">6</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre">     DEDUCTIBLE AMOUNT PER CLAIM/ACCIDENT: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="dedamt"/></xsl:with-param><xsl:with-param name="len">9</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>             DEDUCTIBLE AMOUNT-AGGREGATE: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="dedaggr"/></xsl:with-param><xsl:with-param name="len">9</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre"> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre"> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre">
</fo:block>
</xsl:template><xsl:template match="record[@name = 'NAMEREC']" xml:space="preserve">
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre" >                                                            ***NAME RECORD***                        POLICY: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="symbol"/></xsl:with-param><xsl:with-param name="len">3</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template><xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="policy0num"/></xsl:with-param><xsl:with-param name="len">7</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre"> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre">     NAME RECORD TYPE.......: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="typerec"/></xsl:with-param><xsl:with-param name="len">1</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>    NAME LINK DATA......: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="linkdata"/></xsl:with-param><xsl:with-param name="len">40</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre">     NAME OF INSURED........: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="nameofins"/></xsl:with-param><xsl:with-param name="len">79</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre"> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre"> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre">
</fo:block>
</xsl:template><xsl:template match="record[@name = 'ADRSREC']" xml:space="preserve">
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre" >                                                            ***ADDRESS RECORD***                     POLICY: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="symbol"/></xsl:with-param><xsl:with-param name="len">3</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template><xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="policy0num"/></xsl:with-param><xsl:with-param name="len">7</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre"> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre">     ADDRESS RECORD TYPE....: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="typerec"/></xsl:with-param><xsl:with-param name="len">1</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>    ADDRESS LINK DATA...: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="linkdata"/></xsl:with-param><xsl:with-param name="len">40</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre">     ADDRESS OF INSURED.....: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="addrofins"/></xsl:with-param><xsl:with-param name="len">79</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre"> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre"> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre">
</fo:block>
</xsl:template><xsl:template match="record[@name = 'EXPOSREC']" xml:space="preserve">
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre" >                                                            ***EXPOSURE RECORD***                    POLICY: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="symbol"/></xsl:with-param><xsl:with-param name="len">3</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template><xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="policy0num"/></xsl:with-param><xsl:with-param name="len">7</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre"> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre">     EXPOSURE RECORD TYPE...: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="rectype"/></xsl:with-param><xsl:with-param name="len">1</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>    EXPOSURE LINK DATA..: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="linkdata"/></xsl:with-param><xsl:with-param name="len">40</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>  FROM RPT: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="frmprvrpt"/></xsl:with-param><xsl:with-param name="len">1</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template> CORR: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="frmprvcorr"/></xsl:with-param><xsl:with-param name="len">1</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre">     EXPOSURE COVERAGE......: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="covcode"/></xsl:with-param><xsl:with-param name="len">2</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>          EXPOSURE CLASS CODE...: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="clscode4"/></xsl:with-param><xsl:with-param name="len">4</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre">     EXPERIENCE MOD.........: <xsl:call-template name="Prepad"><xsl:with-param name="padVar"><xsl:value-of select="emod"/></xsl:with-param><xsl:with-param name="len">4</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>        MANUAL RATE...........: <xsl:call-template name="Prepad"><xsl:with-param name="padVar"><xsl:value-of select="manrate"/></xsl:with-param><xsl:with-param name="len">7</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre">     MOD EFFECTIVE DATE.....: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="emodyy"/></xsl:with-param><xsl:with-param name="len">2</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>/<xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="emodmm"/></xsl:with-param><xsl:with-param name="len">2</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>/<xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="emoddd"/></xsl:with-param><xsl:with-param name="len">2</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>    RATE EFFECTIVE DATE...: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="rateyy"/></xsl:with-param><xsl:with-param name="len">2</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>/<xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="ratemm"/></xsl:with-param><xsl:with-param name="len">2</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>/<xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="ratedd"/></xsl:with-param><xsl:with-param name="len">2</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre">     EXPOSURE AMOUNT........: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="expamt"/></xsl:with-param><xsl:with-param name="len">10</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>  PREMIUM AMOUNT........: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="premamt"/></xsl:with-param><xsl:with-param name="len">9</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre">     SPLIT PERIOD IND.......: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="splitind"/></xsl:with-param><xsl:with-param name="len">1</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>           UPDATE TYPE...........: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="updatetype"/></xsl:with-param><xsl:with-param name="len">1</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre"> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre"> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre">
</fo:block>
</xsl:template><xsl:template match="record[@name = 'LOSSREC']" xml:space="preserve">
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre" >                                                            ***LOSS RECORD***                        POLICY: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="symbol"/></xsl:with-param><xsl:with-param name="len">3</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template><xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="policy0num"/></xsl:with-param><xsl:with-param name="len">7</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre"> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre">     LOSS RECORD TYPE.......: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="rectype"/></xsl:with-param><xsl:with-param name="len">1</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>    LOSS LINK DATA......: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="linkdata"/></xsl:with-param><xsl:with-param name="len">40</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>  FROM RPT: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="frmprvrpt"/></xsl:with-param><xsl:with-param name="len">1</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template> CORR: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="frmprvcorr"/></xsl:with-param><xsl:with-param name="len">1</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre">     CLASS CODE.............: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="clscode4"/></xsl:with-param><xsl:with-param name="len">4</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>                                              CLAIM STATUS......: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="clmstatus"/></xsl:with-param><xsl:with-param name="len">1</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>         NUMBER OF CLAIMS: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="noclaims"/></xsl:with-param><xsl:with-param name="len">4</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre">     CLAIM NUMBER.........: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="claim"/></xsl:with-param><xsl:with-param name="len">12</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>  ACCIDENT DATE.........: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="accdateyy"/></xsl:with-param><xsl:with-param name="len">2</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>/<xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="accdatemm"/></xsl:with-param><xsl:with-param name="len">2</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>/<xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="accdatedd"/></xsl:with-param><xsl:with-param name="len">2</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>      INJURY TYPE.......: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="injcode"/></xsl:with-param><xsl:with-param name="len">2</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre">     INCURRED INDEMNITY AMT.: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="indamt"/></xsl:with-param><xsl:with-param name="len">9</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>   INCURRED MEDICAL AMT..: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="medamt"/></xsl:with-param><xsl:with-param name="len">9</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>     CATASTROPHE NUMBER: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="catno"/></xsl:with-param><xsl:with-param name="len">2</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>        LUMP SUM INDICATOR: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="lumpsum"/></xsl:with-param><xsl:with-param name="len">1</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre">                                                                                MANAGED CARE ORGANIZATION TYPE:  <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="mcoind"/></xsl:with-param><xsl:with-param name="len">2</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre">     UPDATE TYPE............: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="updatetype"/></xsl:with-param><xsl:with-param name="len">1</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>           ACT...................: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="act"/></xsl:with-param><xsl:with-param name="len">2</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>            TYPE OF LOSS......: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="typeloss"/></xsl:with-param><xsl:with-param name="len">2</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>        TYPE OF RECOVERY: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="typerecv"/></xsl:with-param><xsl:with-param name="len">2</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre">     TYPE OF CLAIM..........: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="typecovg"/></xsl:with-param><xsl:with-param name="len">2</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>          TYPE OF SETTLEMENT....: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="typesetmt"/></xsl:with-param><xsl:with-param name="len">2</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>            JURISDICTION STATE  <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="lsstjuris"/></xsl:with-param><xsl:with-param name="len">2</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre">     PART OF BODY...........: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="bodypart"/></xsl:with-param><xsl:with-param name="len">2</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>          NATURE OF INJURY......: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="natureinj"/></xsl:with-param><xsl:with-param name="len">2</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>            CAUSE OF INJURY...: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="causeinj"/></xsl:with-param><xsl:with-param name="len">2</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>        VOCATIONAL REHAB: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="vocational"/></xsl:with-param><xsl:with-param name="len">1</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre">     FRAUDULENT CLAIM IND...: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="fraudclaim"/></xsl:with-param><xsl:with-param name="len">2</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>          SOCIAL SECURITY NUMBER: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="socsecno"/></xsl:with-param><xsl:with-param name="len">9</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>     PAID INDEMNITY AMT: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="paidindamt"/></xsl:with-param><xsl:with-param name="len">9</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre">     PAID ALAE AMT..........: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="pdalaeamt"/></xsl:with-param><xsl:with-param name="len">9</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>   INCURRED ALAE AMT.....: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="inalaeamt"/></xsl:with-param><xsl:with-param name="len">9</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>     PAID MEDICAL AMT:   <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="paidmedamt"/></xsl:with-param><xsl:with-param name="len">9</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre">     DEDUCTIBLE REIMBURSEMENT: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="dedreimb"/></xsl:with-param><xsl:with-param name="len">9</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>  OCCUPATION DESCRIPTION: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="occdesc"/></xsl:with-param><xsl:with-param name="len">18</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre"> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre"> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre">
</fo:block>
</xsl:template><xsl:template match="record[@name = 'UNITTOTREC']" xml:space="preserve">
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre" >                                                            ***UNIT TOTAL RECORD***                  POLICY: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="symbol"/></xsl:with-param><xsl:with-param name="len">3</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template><xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="policy0num"/></xsl:with-param><xsl:with-param name="len">7</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre"> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre">     UNIT TOTAL RECORD TYPE..: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="rectype"/></xsl:with-param><xsl:with-param name="len">1</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>   UNIT TOTAL LINK DATA: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="linkdata"/></xsl:with-param><xsl:with-param name="len">40</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre"> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre">     TOTAL STANDARD EXPOSURE.: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="exppayroll"/></xsl:with-param><xsl:with-param name="len">11</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre">     TOTAL SUBJECT PREMIUM...: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="subjprem"/></xsl:with-param><xsl:with-param name="len">10</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>          TOTAL STANDARD PREMIUM...........: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="stanprem"/></xsl:with-param><xsl:with-param name="len">11</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre">     TOTAL NUMBER OF CLAIMS..: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="noclmtot"/></xsl:with-param><xsl:with-param name="len">5</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre">     TOTAL INCURRED INDEMNITY: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="inindtot"/></xsl:with-param><xsl:with-param name="len">10</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>          TOTAL INCURRED MEDICAL...........: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="inmedtot"/></xsl:with-param><xsl:with-param name="len">10</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre">     TOTAL NUMBER OF RECORDS IN UNIT REPORT: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="norectot"/></xsl:with-param><xsl:with-param name="len">5</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre">     TOTAL PAID INDEMNITY....: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="pdindtot"/></xsl:with-param><xsl:with-param name="len">10</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>          TOTAL PAID MEDICAL...............: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="pdmedtot"/></xsl:with-param><xsl:with-param name="len">10</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre">     TOTAL ALAE PAID.........: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="pdalaetot"/></xsl:with-param><xsl:with-param name="len">10</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>          TOTAL ALAE INCURRED..............: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="inalaetot"/></xsl:with-param><xsl:with-param name="len">10</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre"> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre"> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre">
</fo:block>
</xsl:template><xsl:template match="record[@name = 'SUBREC']" xml:space="preserve">
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre" >                                                     ***SUBMISSION CONTROL RECORD*** </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre"> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre">     SUBMISSION CONTROL RECORD TYPE: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="rectype"/></xsl:with-param><xsl:with-param name="len">1</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>             DETAILED RECORD COUNT.......: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="detailcnt"/></xsl:with-param><xsl:with-param name="len">8</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre">     ASWG TAPE SUBMISSION INDICATOR: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="aswgind"/></xsl:with-param><xsl:with-param name="len">1</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>             TOTAL UNIT REPORTS SUBMITTED: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="unittot"/></xsl:with-param><xsl:with-param name="len">7</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>
</fo:block>
</xsl:template><xsl:template match="record[@name = 'BNRHEAD']" xml:space="preserve">
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre" > PMSPUST02 </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre">                                         UNIT STATISTICAL REPORTING </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre">                                         SYSTEM RUN DATE: <xsl:call-template name="cvtdateCYYMMDDtoMMDDYY"><xsl:with-param name="datefld"><xsl:call-template name="Prepad"><xsl:with-param name="padVar"><xsl:value-of select="enddate"/></xsl:with-param><xsl:with-param name="len">6</xsl:with-param><xsl:with-param name="padChar">0</xsl:with-param></xsl:call-template></xsl:with-param></xsl:call-template> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre">                                         RUN PRODUCED FOR: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="runburcode"/></xsl:with-param><xsl:with-param name="len">4</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre"> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre">                                                       ********************* </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre">                                                       *    BEG OF REPORT  * </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre">                                                       *    END OF REPORT  * </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre">                                                       ********************* </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre">
</fo:block>
</xsl:template><xsl:template match="record[@name = 'NODATA']" xml:space="preserve">
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre" > </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre"> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre"> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre"> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre">                    ** NO STATISTICAL INFORMATION TO BE REPORTED **
</fo:block>
</xsl:template></xsl:stylesheet>