<?xml version="1.0" encoding="ISO-8859-1"?>

<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                              xmlns:fo="http://www.w3.org/1999/XSL/Format"
                              xmlns:fn="http://www.w3.org/2005/02/xpath-functions">
	<xsl:include href="ConvertDateCYYMMDDtoMMDDYYYY.xsl"/>
	<xsl:include href="ConvertDateCYYMMDDtoMMDDYY.xsl"/>
	<xsl:include href="ConvertTimeHHMMSS.xsl"/>
	<xsl:include href="Prepad.xsl"/>
	<xsl:include href="Postpad.xsl"/>
	<xsl:param name="date"/>
	<xsl:param name="time"/>
	<xsl:output encoding="UTF-8"/>
	<xsl:preserve-space elements="*"/>

    <xsl:template match="/">
        <fo:root>
            <fo:layout-master-set>
                <fo:simple-page-master master-name="LandscapeReport"
                    page-width="11in"
                    page-height="8.5in"
                    margin-top=".17in"
                    margin-bottom=".17in"
                    margin-left=".25in"
                    margin-right=".25in">
                    <fo:region-body margin-top="0in"/>
                    <fo:region-before extent="0in"/>
                    <fo:region-after  extent="0in"/>
                </fo:simple-page-master>
                <fo:simple-page-master master-name="PortraitReport"
                    page-width="8.5in"
                    page-height="11in"
                    margin-top=".25in"
                    margin-bottom=".25in"
                    margin-left=".17in"
                    margin-right=".17in">
                    <fo:region-body margin-top="0in"/>
                    <fo:region-before extent="0in"/>
                    <fo:region-after  extent="0in"/>
                </fo:simple-page-master>
            </fo:layout-master-set>

            <fo:page-sequence master-reference="LandscapeReport">
                <fo:flow flow-name="xsl-region-body">
                <xsl:apply-templates select="/POINTXML/file/record"/>
                </fo:flow>
            </fo:page-sequence>

        </fo:root>
    </xsl:template>

<!-- Auto Generated XSLT for printer file DDS PMSPDCI21-->
<xsl:template match="record[@name = 'HEADER1']" xml:space="preserve">
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre" > PMSDCI                                        DETAILED CLAIM INFORMATION (DCI) REPORT                                PAGE:      <fo:page-number/> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre">                                                                                                                      DATE:  <xsl:value-of select="$date"/> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre">                                                                                                                      TIME:  <xsl:value-of select="$time"/> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre"> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre"> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre"> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre">
</fo:block>
</xsl:template><xsl:template match="record[@name = 'RECTYPE1']" xml:space="preserve">
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre" > RECTYPE: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="rectype"/></xsl:with-param><xsl:with-param name="len">1</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template> CARRIER CODE: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="carriercd"/></xsl:with-param><xsl:with-param name="len">5</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>   POLICY: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="policy"/></xsl:with-param><xsl:with-param name="len">18</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>  EFFECTIVE DATE: <xsl:call-template name="cvtdateCYYMMDDtoMMDDYY"><xsl:with-param name="datefld"><xsl:call-template name="Prepad"><xsl:with-param name="padVar"><xsl:value-of select="poleffdte"/></xsl:with-param><xsl:with-param name="len">6</xsl:with-param><xsl:with-param name="padChar">0</xsl:with-param></xsl:call-template></xsl:with-param></xsl:call-template>   CLAIM NUMBER: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="claim"/></xsl:with-param><xsl:with-param name="len">18</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre"> REPORT TYPE............ <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="reporttype"/></xsl:with-param><xsl:with-param name="len">2</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>       TRANSACTION TYPE.... <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="transcode"/></xsl:with-param><xsl:with-param name="len">1</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>      STATE OF JURISDICTION: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="statejud"/></xsl:with-param><xsl:with-param name="len">2</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre"> ACCIDENT STATE......... <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="stateacc"/></xsl:with-param><xsl:with-param name="len">2</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>       DATE REPORTED.: <xsl:call-template name="cvtdateCYYMMDDtoMMDDYY"><xsl:with-param name="datefld"><xsl:call-template name="Prepad"><xsl:with-param name="padVar"><xsl:value-of select="reportdate"/></xsl:with-param><xsl:with-param name="len">6</xsl:with-param><xsl:with-param name="padChar">0</xsl:with-param></xsl:call-template></xsl:with-param></xsl:call-template>    SSN........... <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="ssn"/></xsl:with-param><xsl:with-param name="len">9</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>   EMPLOYER''S TAX ID..<xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="taxnbr"/></xsl:with-param><xsl:with-param name="len">9</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre"> SIC CODE............... <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="siccode"/></xsl:with-param><xsl:with-param name="len">6</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>   PAYROLL............. <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="payroll"/></xsl:with-param><xsl:with-param name="len">1</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>      ZIP CODE.......... <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="zipcode"/></xsl:with-param><xsl:with-param name="len">5</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>   EMPLOYEE''S LAST NAME<xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="emplastnm"/></xsl:with-param><xsl:with-param name="len">6</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre"> EMPLOYEE''S FIRST INITIAL<xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="empfstint"/></xsl:with-param><xsl:with-param name="len">1</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>       SEX................. <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="sex"/></xsl:with-param><xsl:with-param name="len">1</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>      MARRIAGE STATUS....... <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="maritalsts"/></xsl:with-param><xsl:with-param name="len">1</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>   DATE OF BIRTH...... <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="dob"/></xsl:with-param><xsl:with-param name="len">6</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre"> DATE HIRED............. <xsl:call-template name="cvtdateCYYMMDDtoMMDDYY"><xsl:with-param name="datefld"><xsl:call-template name="Prepad"><xsl:with-param name="padVar"><xsl:value-of select="hiredate"/></xsl:with-param><xsl:with-param name="len">6</xsl:with-param><xsl:with-param name="padChar">0</xsl:with-param></xsl:call-template></xsl:with-param></xsl:call-template> OCCUPATION CODE..... <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="occcode"/></xsl:with-param><xsl:with-param name="len">2</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>     EMPLOYMENT STATUS..... <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="empstatus"/></xsl:with-param><xsl:with-param name="len">1</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>   DATE INJURED....... <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="dateinjury"/></xsl:with-param><xsl:with-param name="len">6</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre"> CLASS CODE............. <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="classcode"/></xsl:with-param><xsl:with-param name="len">4</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>     BODY PART........... <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="bodypart"/></xsl:with-param><xsl:with-param name="len">2</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>     INJURY NATURE........ <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="injnature"/></xsl:with-param><xsl:with-param name="len">2</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>   INJURY CAUSE....... <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="injcause"/></xsl:with-param><xsl:with-param name="len">2</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre"> LOSS COVERAGE CODE..... <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="losscovcd"/></xsl:with-param><xsl:with-param name="len">2</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>       NUMBER OF DEPENDENTS <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="dependants"/></xsl:with-param><xsl:with-param name="len">2</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>     WEEKLY WAGE...... <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="weeklywage"/></xsl:with-param><xsl:with-param name="len">5</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>    DETERMINE WAGE..... <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="detwage"/></xsl:with-param><xsl:with-param name="len">1</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre"> OTHER WEEKLY WAGE...... <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="othwkpay"/></xsl:with-param><xsl:with-param name="len">5</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>    DATE REPORTED TO EMPLOYER: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="rptdateemp"/></xsl:with-param><xsl:with-param name="len">6</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>                      SURGERY............ <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="surgery"/></xsl:with-param><xsl:with-param name="len">1</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre"> CLAIM STATUS........... <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="claimsts"/></xsl:with-param><xsl:with-param name="len">1</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>        CLOSE DATE....: <xsl:call-template name="cvtdateCYYMMDDtoMMDDYY"><xsl:with-param name="datefld"><xsl:call-template name="Prepad"><xsl:with-param name="padVar"><xsl:value-of select="closedate"/></xsl:with-param><xsl:with-param name="len">6</xsl:with-param><xsl:with-param name="padChar">0</xsl:with-param></xsl:call-template></xsl:with-param></xsl:call-template>    FIRST PAYMENT DATE: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="date1stpay"/></xsl:with-param><xsl:with-param name="len">6</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre"> DATE DISABILITY BEGAN.. <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="datedisbgn"/></xsl:with-param><xsl:with-param name="len">6</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>   DATE RETURNED TO WORK: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="dateretwrk"/></xsl:with-param><xsl:with-param name="len">6</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre"> LOSS CONDITIONS: ACT... <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="lcact"/></xsl:with-param><xsl:with-param name="len">2</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>   TYPE LOSS <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="lctyploss"/></xsl:with-param><xsl:with-param name="len">2</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>   TYPE RECOVERY <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="lctyprecov"/></xsl:with-param><xsl:with-param name="len">2</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>   TYPE COVERAGE <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="lctypcover"/></xsl:with-param><xsl:with-param name="len">2</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>   TYPE SETTLEMENT <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="lctypsettl"/></xsl:with-param><xsl:with-param name="len">2</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre"> TOTAL INCUR. INDEMNITY: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="totincindm"/></xsl:with-param><xsl:with-param name="len">8</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre"> BENEFITS:               1              2              3              4              5 </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre">   INJURY CODING        <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="bnfittype1"/></xsl:with-param><xsl:with-param name="len">2</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>             <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="bnfittype2"/></xsl:with-param><xsl:with-param name="len">2</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>             <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="bnfittype3"/></xsl:with-param><xsl:with-param name="len">2</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>             <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="bnfittype4"/></xsl:with-param><xsl:with-param name="len">2</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>             <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="bnfittype5"/></xsl:with-param><xsl:with-param name="len">2</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre">   PAID          <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="bnfitpd1"/></xsl:with-param><xsl:with-param name="len">7</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>        <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="bnfitpd2"/></xsl:with-param><xsl:with-param name="len">7</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>        <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="bnfitpd3"/></xsl:with-param><xsl:with-param name="len">7</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>        <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="bnfitpd4"/></xsl:with-param><xsl:with-param name="len">7</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>        <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="bnfitpd5"/></xsl:with-param><xsl:with-param name="len">7</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre">   WEEK             <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="wkbnfit1"/></xsl:with-param><xsl:with-param name="len">5</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>          <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="wkbnfit2"/></xsl:with-param><xsl:with-param name="len">5</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>          <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="wkbnfit3"/></xsl:with-param><xsl:with-param name="len">5</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>          <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="wkbnfit4"/></xsl:with-param><xsl:with-param name="len">5</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>          <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="wkbnfit5"/></xsl:with-param><xsl:with-param name="len">5</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre"> VOCATIONAL REHABILITATION: </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre"> TOTAL INCURED <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="vocinc"/></xsl:with-param><xsl:with-param name="len">8</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>       EVALUATION EXPENSE <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="vocevalexp"/></xsl:with-param><xsl:with-param name="len">7</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>    MAINT. PAID <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="vocpd"/></xsl:with-param><xsl:with-param name="len">7</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>    EDUCATION EXPENSE <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="voceduexp"/></xsl:with-param><xsl:with-param name="len">7</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>     OTHER <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="vocothpd"/></xsl:with-param><xsl:with-param name="len">7</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre"> TOTAL MEDICAL <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="totincmed"/></xsl:with-param><xsl:with-param name="len">8</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>       HOSPITAL COST..... <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="hosppaid"/></xsl:with-param><xsl:with-param name="len">7</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>    PHYSICIANS. <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="doctorpay"/></xsl:with-param><xsl:with-param name="len">7</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>    OTHER MEDICAL.... <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="othmedpay"/></xsl:with-param><xsl:with-param name="len">7</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre"> POST INJURY WEEKLY WAGE <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="postwkwage"/></xsl:with-param><xsl:with-param name="len">5</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>               PERCENTAGE OF IMPAIRMENT. <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="pctnimpair"/></xsl:with-param><xsl:with-param name="len">3</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>           DATE OF MAX MEDICAL IMPROVEMENT: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="datemaximp"/></xsl:with-param><xsl:with-param name="len">6</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre"> FUNERAL EXPENSES....... <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="funeralexp"/></xsl:with-param><xsl:with-param name="len">6</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>              LUMP SUM................. <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="lumpsum"/></xsl:with-param><xsl:with-param name="len">8</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>      EMPLOYER LIABILITY PAID..... <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="liapaid"/></xsl:with-param><xsl:with-param name="len">8</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre"> DEDUCTIBLE CODE........ <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="deductible"/></xsl:with-param><xsl:with-param name="len">2</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>                  ATTORNEY................. <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="attorney"/></xsl:with-param><xsl:with-param name="len">1</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>             CONTROVERTED CASE........... <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="contvcase"/></xsl:with-param><xsl:with-param name="len">1</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre"> DEDUCTIBLE(EMPLR REIMB) <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="deductbl95"/></xsl:with-param><xsl:with-param name="len">1</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>                   SUBROGATION PRODUCT LIAB. <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="prodliasub"/></xsl:with-param><xsl:with-param name="len">7</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>       AUTOMOBILE LIABILITY........ <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="autoliasub"/></xsl:with-param><xsl:with-param name="len">7</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre"> OTHER LIABILITY........ <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="othrliasub"/></xsl:with-param><xsl:with-param name="len">7</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>             EMPLOYER LEGAL EXPENSES.. <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="emprlegal"/></xsl:with-param><xsl:with-param name="len">7</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>       CLAIMANT LEGAL EXPENSES....  <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="clmntlegal"/></xsl:with-param><xsl:with-param name="len">7</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre"> EXPERT WITNESS FEES.... <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="witnessfee"/></xsl:with-param><xsl:with-param name="len">6</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>              PENALTIES................ <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="penalties"/></xsl:with-param><xsl:with-param name="len">6</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>        ALLOCATED LOSS ADJUSTMENT... <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="lossadjexp"/></xsl:with-param><xsl:with-param name="len">7</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre"> SOCIAL SECURITY <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="socsecoff"/></xsl:with-param><xsl:with-param name="len">1</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>    UNEMPLOYMENT <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="unempoff"/></xsl:with-param><xsl:with-param name="len">1</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>    PENSION PLAN <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="pensionoff"/></xsl:with-param><xsl:with-param name="len">1</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>    SPECIAL FUND <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="splfundoff"/></xsl:with-param><xsl:with-param name="len">1</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>    OTHER <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="othoff"/></xsl:with-param><xsl:with-param name="len">1</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>  MANAGED CARE INDICATOR...... <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="mcoind"/></xsl:with-param><xsl:with-param name="len">2</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre"> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre"> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre"> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre">
</fo:block>
</xsl:template><xsl:template match="record[@name = 'RECTYPE2']" xml:space="preserve">
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre" >  <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="carriercd"/></xsl:with-param><xsl:with-param name="len">5</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>       <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="transcode"/></xsl:with-param><xsl:with-param name="len">1</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>    <xsl:call-template name="cvtdateCYYMMDDtoMMDDYY"><xsl:with-param name="datefld"><xsl:call-template name="Prepad"><xsl:with-param name="padVar"><xsl:value-of select="reportdate"/></xsl:with-param><xsl:with-param name="len">4</xsl:with-param><xsl:with-param name="padChar">0</xsl:with-param></xsl:call-template></xsl:with-param></xsl:call-template>     <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="statejud"/></xsl:with-param><xsl:with-param name="len">2</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>    <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="indemclms"/></xsl:with-param><xsl:with-param name="len">5</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>      <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="potendci"/></xsl:with-param><xsl:with-param name="len">5</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>       <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="openindem"/></xsl:with-param><xsl:with-param name="len">5</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>     <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="clspermpar"/></xsl:with-param><xsl:with-param name="len">5</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>        <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="clsnonperm"/></xsl:with-param><xsl:with-param name="len">5</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>       <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="clssample"/></xsl:with-param><xsl:with-param name="len">5</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>   <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="totaldci"/></xsl:with-param><xsl:with-param name="len">5</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre"> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre">
</fo:block>
</xsl:template><xsl:template match="record[@name = 'HEADER2']" xml:space="preserve">
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre" > RECTYPE: 2 </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre"> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre">                                                                    CLOSED       CLOSED              TOTAL </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre">            TRANS  REPORT           TOTAL    POTENTIAL     OPEN    PERMANENT  NON PERMANENT  CLOSED  CLAIMS </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre"> CARRIER     CODE   DATE   STATE  INDEMNITY     DCI      INDEMNITY  PARTIAL      PARTIAL     PULLED  PULLED </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre"> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre"> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre">
</fo:block>
</xsl:template><xsl:template match="record[@name = 'RECTYPE3']" xml:space="preserve">
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre" > RECTYPE: <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="rectype"/></xsl:with-param><xsl:with-param name="len">1</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template> PREVIOUS: CARRIER CODE <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="pcarriercd"/></xsl:with-param><xsl:with-param name="len">5</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>   POLICY NUMBER <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="prevpolicy"/></xsl:with-param><xsl:with-param name="len">18</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>   CLAIM NUMBER<xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="prevclaim"/></xsl:with-param><xsl:with-param name="len">18</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>   DATE REPORTED <xsl:call-template name="cvtdateCYYMMDDtoMMDDYY"><xsl:with-param name="datefld"><xsl:call-template name="Prepad"><xsl:with-param name="padVar"><xsl:value-of select="prvrptdate"/></xsl:with-param><xsl:with-param name="len">6</xsl:with-param><xsl:with-param name="padChar">0</xsl:with-param></xsl:call-template></xsl:with-param></xsl:call-template> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre">                      STATE OF JURISDICTION <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="prvstate"/></xsl:with-param><xsl:with-param name="len">2</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre">            REVISED.: CARRIER CODE <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="carriercd"/></xsl:with-param><xsl:with-param name="len">5</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>   POLICY NUMBER <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="policy"/></xsl:with-param><xsl:with-param name="len">18</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>   CLAIM NUMBER<xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="claim"/></xsl:with-param><xsl:with-param name="len">18</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template>   DATE REPORTED <xsl:call-template name="cvtdateCYYMMDDtoMMDDYY"><xsl:with-param name="datefld"><xsl:call-template name="Prepad"><xsl:with-param name="padVar"><xsl:value-of select="rptdate"/></xsl:with-param><xsl:with-param name="len">6</xsl:with-param><xsl:with-param name="padChar">0</xsl:with-param></xsl:call-template></xsl:with-param></xsl:call-template> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre">                      STATE OF JURISDICTION <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="state"/></xsl:with-param><xsl:with-param name="len">2</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre">            DELETION REASON CODE <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="reason"/></xsl:with-param><xsl:with-param name="len">2</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre"> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre">
</fo:block>
</xsl:template><xsl:template match="record[@name = 'RECTYPE9']" xml:space="preserve">
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre" > RECORD COUNT BY TYPES </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre"> RECORD TYPE 1:     <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="rectype1"/></xsl:with-param><xsl:with-param name="len">7</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre"> RECORD TYPE 2:     <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="rectype2"/></xsl:with-param><xsl:with-param name="len">7</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre"> RECORD TYPE 3:     <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="rectype3"/></xsl:with-param><xsl:with-param name="len">7</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre"> ALL RECORD TYPES   <xsl:call-template name="Postpad"><xsl:with-param name="padVar"><xsl:value-of select="rectypeall"/></xsl:with-param><xsl:with-param name="len">7</xsl:with-param><xsl:with-param name="padChar"> </xsl:with-param></xsl:call-template> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre"> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre"> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre"> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre">
</fo:block>
</xsl:template><xsl:template match="record[@name = 'BNRHEAD']" xml:space="preserve">
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre" > PMSDCI                                                                                                              PAGE:       <fo:page-number/> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre">                                                       DCI REPORT AS                                                 DATE:   <xsl:value-of select="$date"/> OF <xsl:call-template name="cvtdateCYYMMDDtoMMDDYY"><xsl:with-param name="datefld"><xsl:call-template name="Prepad"><xsl:with-param name="padVar"><xsl:value-of select="enddate"/></xsl:with-param><xsl:with-param name="len">4</xsl:with-param><xsl:with-param name="padChar">0</xsl:with-param></xsl:call-template></xsl:with-param></xsl:call-template> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre">                                                                                                                     TIME:   <xsl:value-of select="$time"/> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre"> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre">                                                       ********************* </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre">                                                       *  BEGIN OF REPORT  * </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre">                                                       *   END OF REPORT   * </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre">                                                       ********************* </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre"> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre">
</fo:block>
</xsl:template><xsl:template match="record[@name = 'NODATA']" xml:space="preserve">
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre" > </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre"> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre"> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre"> </fo:block>
<fo:block text-align="justify" font-size="9pt" font-family="monospace" line-height="9pt" white-space="pre">                    ** NO RECORDS SELECTED FOR DATES REQUESTED **
</fo:block>
</xsl:template></xsl:stylesheet>